###
# block routes
###
kitpages_cms:
    pattern:  /block
    defaults: { _controller: KitpagesCmsBundle:Block:view }

kitpages_cms_block_create:
    pattern:  /block/create
    defaults: { _controller: KitpagesCmsBundle:Block:create }

kitpages_cms_block_edit_success:
    pattern:  /block/edit-success
    defaults: { _controller: KitpagesCmsBundle:Block:editSuccess }

kitpages_cms_block_edit:
    pattern:  /block/edit/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:edit }
    requirements:
        id: \d+

kitpages_cms_block_delete:
    pattern:  /block/delete/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:delete }
    requirements:
        id: \d+

kitpages_cms_block_publish:
    pattern:  /block/publish/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:publish }
    requirements:
        id: \d+

kitpages_cms_zoneblock_delete:
    pattern:  /block/zoneBlockDelete/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:zoneBlockDelete }
    requirements:
        id: \d+


###
# Zones
###
kitpages_cms_zoneblock_moveup:
    pattern:  /zone/moveup/{id}/{block_id}
    defaults: { _controller: KitpagesCmsBundle:Zone:moveUpBlock }
    requirements:
        id: \d+

kitpages_cms_zoneblock_movedown:
    pattern:  /zone/movedown/{id}/{block_id}
    defaults: { _controller: KitpagesCmsBundle:Zone:moveDownBlock }
    requirements:
        id: \d+
        
kitpages_cms_zone_create:
    pattern:  /zone/create
    defaults: { _controller: KitpagesCmsBundle:Zone:create }         

kitpages_cms_zone_publish:
    pattern:  /zone/publish/{id}
    defaults: { _controller: KitpagesCmsBundle:Zone:publish }    
    requirements:
        id: \d+

###
# Admin
###
kitpages_cms_admin_view_mode_change:
    pattern:  /admin/viewModeChange/{viewMode}
    defaults: { _controller: KitpagesCmsBundle:Admin:viewModeChange }
    requirements:
        id: \d+

###
# Pages
###
kitpages_cms_page_create:
    pattern:  /page/create
    defaults: { _controller: KitpagesCmsBundle:Page:create }        

kitpages_cms_page_create_technical:
    pattern:  /page/createTechnical
    defaults: { _controller: KitpagesCmsBundle:Page:createTechnical } 

kitpages_cms_page_create_link:
    pattern:  /page/createLink
    defaults: { _controller: KitpagesCmsBundle:Page:createLink } 

kitpages_cms_page_edit:
    pattern:  /page/edit/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:edit }  
    requirements:
        id: \d+
 
kitpages_cms_page_edit_technical:
    pattern:  /page/editTechnical/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:editTechnical }  
    requirements:
        id: \d+        
   
kitpages_cms_page_edit_link:
    pattern:  /page/editLink/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:editLink }  
    requirements:
        id: \d+ 
        
kitpages_cms_page_view:
    pattern:  /page/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:view }
    requirements:
        id: \d+


kitpages_cms_page_publish:
    pattern:  /page/publish/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:publish }
    requirements:
        id: \d+

kitpages_cms_page_delete:
    pattern:  /page/delete/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:delete }
    requirements:
        id: \d+

kitpages_cms_page_arbo:
    pattern:  /arbo
    defaults: { _controller: KitpagesCmsBundle:Page:arbo }
    
kitpages_cms_page_moveup:
    pattern:  /page/moveup/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:moveUp }  
    requirements:
        id: \d+
        
kitpages_cms_page_movedown:
    pattern:  /page/movedown/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:moveDown }  
    requirements:
        id: \d+
