kitpages_cms:
    pattern:  /block
    defaults: { _controller: KitpagesCmsBundle:Block:view }

kitpages_cms_block_create:
    pattern:  /block/create
    defaults: { _controller: KitpagesCmsBundle:Block:create }
    
kitpages_cms_block_edit:
    pattern:  /block/edit/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:edit }
    requirements:
        id: \d+
