kitpages_cms:
    pattern:  /block
    defaults: { _controller: KitpagesCmsBundle:Block:view }

kitpages_cms_block_create:
    pattern:  /block/create
    defaults: { _controller: KitpagesCmsBundle:Block:create }

kitpages_cms_block_edit_success:
    pattern:  /block/edit-success
    defaults: { _controller: KitpagesCmsBundle:Block:editSuccess }

kitpages_cms_block_edit:
    pattern:  /block/edit/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:edit }
    requirements:
        id: \d+

kitpages_cms_zoneblock_delete:
    pattern:  /block/zoneBlockDelete/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:zoneBlockDelete }
    requirements:
        id: \d+
 
kitpages_cms_zoneblock_moveup:
    pattern:  /block/moveup/{zone}/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:moveUp }
    requirements:
        id: \d+

kitpages_cms_zoneblock_movedown:
    pattern:  /block/movedown/{zone}/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:moveDown }
    requirements:
        id: \d+
        
kitpages_cms_block_publish:
    pattern:  /block/publish/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:publish }
    requirements:
        id: \d+
        
kitpages_cms_block_unpublish:
    pattern:  /block/unpublish/{id}
    defaults: { _controller: KitpagesCmsBundle:Block:unpublish }
    requirements:
        id: \d+
        
kitpages_cms_admin_view_mode_change:
    pattern:  /admin/viewModeChange/{viewMode}
    defaults: { _controller: KitpagesCmsBundle:Admin:viewModeChange }
    requirements:
        id: \d+

kitpages_cms_page_create:
    pattern:  /page/create
    defaults: { _controller: KitpagesCmsBundle:Page:create }        
        
kitpages_cms_page_view:
    pattern:  /page/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:view }
    requirements:
        id: \d+
 
kitpages_cms_page_publish:
    pattern:  /page/publish/{id}
    defaults: { _controller: KitpagesCmsBundle:Page:publish }
    requirements:
        id: \d+
        
kitpages_cms_zone_create:
    pattern:  /zone/create
    defaults: { _controller: KitpagesCmsBundle:Zone:create }         
    
kitpages_cms_zone_publish:
    pattern:  /zone/publish/{id}
    defaults: { _controller: KitpagesCmsBundle:Zone:publish }    
    requirements:
        id: \d+
